### ISSUE TITLE
Комментарии по semant

### ISSUE THREAD

**Issue by dbezhetskov** [xp10rd/coolc#1]
1.
Почему бы не вынести класс Scope в отдельный файл?
https://github.com/gafiyatullin-a/Compilers/blob/da6b673f9d5a7e72c02b19a6f744dab5ac503850/Compilers-Alex-Aiken/include/semant/Semant.h#L28
2.
Можем ли эту константу определить как constexpr и в .cpp файле и не светить её на уровне класса?
https://github.com/gafiyatullin-a/Compilers/blob/da6b673f9d5a7e72c02b19a6f744dab5ac503850/Compilers-Alex-Aiken/include/semant/Semant.h#L34
3.
Если нам больше потом этот vector не нужен, тогда может мы его mov'нем внутрь Semant?
https://github.com/gafiyatullin-a/Compilers/blob/da6b673f9d5a7e72c02b19a6f744dab5ac503850/Compilers-Alex-Aiken/include/semant/Semant.h#L157
4.
Не проше ли оставить один add который всегда возвращает ваш ADD_RESULT?
https://github.com/gafiyatullin-a/Compilers/blob/da6b673f9d5a7e72c02b19a6f744dab5ac503850/Compilers-Alex-Aiken/include/semant/Semant.h#L46

**Comment by dbezhetskov** [comment]
Ну и main можно было вынести тоже в другой файл:
https://github.com/gafiyatullin-a/Compilers/blob/main/Compilers-Alex-Aiken/src/semant/Semant.cpp#L1044

Все в один файл это не то, к чему надо стремиться :)

**Comment by a-gafiyatullin** [comment]
Касательно move не совсем понял, куда нужно move-нуть вектор. Вектор деревьев в конструкторе всё равно нужно будет перестроить в одно дерево, и я в итоге и внутри класса тоже не использую изначальный массив.

**Comment by dbezhetskov** [comment]
> Касательно move не совсем понял, куда нужно move-нуть вектор
```
explicit Semant(std::vector<std::shared_ptr<ast::Program>> programs);
```
и потом тут
https://github.com/gafiyatullin-a/Compilers/blob/da6b673f9d5a7e72c02b19a6f744dab5ac503850/Compilers-Alex-Aiken/src/semant/Semant.cpp#L1061

```
Semant semant(std::move(programs));
```

**Comment by a-gafiyatullin** [comment]
Поменял) Хотя всё равно не совсем понял, какие это преимущества дает по сравнению с передачей по ссылке

**Comment by dbezhetskov** [comment]
Тем, что после конструирования `Semant` вы больше не пользуетесь `programs`. И память под `programs` освободится сразу по окончанию работы семанта.

**Comment by a-gafiyatullin** [comment]
Окей, понял теперь) Всё остальное тоже поправил.
