### ISSUE TITLE
Compiler crashes: Unexpected null character in regular expression

### ISSUE THREAD

**Issue by Kakadu** [xp10rd/coolc#7]
https://github.com/xp10rd/coolc/blob/main/coolc/src/lexer/Lexer.cpp#L5

I tried llvm11 and llvm 15. The same crash

@xp10rd

**Comment by a-gafiyatullin** [comment]
@Kakadu Can you please provide OS version, build and run commands?

**Comment by Kakadu** [comment]
> @Kakadu Can you please provide OS version, build and run commands?

https://gist.github.com/Kakadu/8c1d62b08adfe61dd1dd492bd6fddb76

**Comment by a-gafiyatullin** [comment]
@Kakadu Sorry, at this moment I don't have a x86 machine with Linux. I checked this issue in Docker with Ubuntu 22.04 where default llvm and clang/clang++ versions are 14.0.0 and all seems ok. You can use Dockerfile to build and run project. From the `coolc` dir run:

`docker build -t ubuntu-22-04-env .`
`docker run --platform linux/amd64 --rm -it -v $(pwd):/home/xp10rd/coolc ubuntu-22-04-env bash`

**Comment by Kakadu** [comment]
It compiles in docker, but I still don't understand what goes wrong on newest Ubuntu's. The only thing that I discovered that fixing the same version of clang++-14 is not enough.
